name: Eleventy Build


on:
  push:
    branches:
      - Dev-Boys_of-the-West
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2


        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '16.17.1'

        - name: Install dependencies and build
          run: |
            npm ci
            npm run build


        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

            publish_dir: ./build
